int Pow2Test();
unsigned long Pow2(unsigned int x, unsigned int y);
int IsPowerOfTwoLoopTest();
int IsPowerOfTwoLoop(unsigned int n);
int IsPowerOfTwoNoLoopTest();
int IsPowerOfTwoNoLoop(unsigned int n);
int AddOne(unsigned int num);
int AddOneTest();
int ThreeBitsNumbers(unsigned int *array, size_t size);
int ThreeBitsNumbersTest();
char ByteMirror(unsigned char n);
int ByteMirrorTest();
char ByteMirrorNoLoop(unsigned char num);
int ByteMirrorNoLoopTest();
int FindSecondORSixthBit(unsigned char num);
int FindSecondSixthBit(unsigned char num);
int FindSecondSixthBitTest();
unsigned char SwapNum(unsigned char num); 
int DevidedBySixteen(unsigned int num);
int DevidedBySixteenTest();
int SwapNumsBitWise(unsigned int *num1, unsigned int *num2);
int SwapNumsBitWiseTest();
int SetBitsCount(int num);
int SetBitsCountTest();
int SetBitsNoLoopCount(int num);
int SetBitsNoLoopCountTest();
int FloatSetBits();
int FloatSetBitsTest();

